spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mariadb://localhost:3308/lmsSys
    driver-class-name: org.mariadb.jdbc.Driver
    username: lms-user
    password: a1234
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: fortestseowon@gmail.com
    password: vxpl unmy hbad vayi
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            
logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

